package main

import (
	"context"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/spf13/cobra"

	"github.com/SchneiderDaniel/cheasee-pi/cmd/cheasee-pi/testutil"
)

// ──────────────────────────────────────────────
// SetDefaultProvider (entity)
// ──────────────────────────────────────────────

func TestSetDefaultProvider_setsBothFields(t *testing.T) {
	s := &Settings{}
	s.SetDefaultProvider("openai", "gpt-4o")
	if s.DefaultProvider != "openai" {
		t.Errorf("DefaultProvider = %q, want openai", s.DefaultProvider)
	}
	if s.DefaultModel != "gpt-4o" {
		t.Errorf("DefaultModel = %q, want gpt-4o", s.DefaultModel)
	}
}

func TestSetDefaultProvider_emptyModelKeepsExisting(t *testing.T) {
	s := &Settings{DefaultModel: "gpt-4o-mini"}
	s.SetDefaultProvider("openai", "")
	if s.DefaultProvider != "openai" {
		t.Errorf("DefaultProvider = %q, want openai", s.DefaultProvider)
	}
	if s.DefaultModel != "gpt-4o-mini" {
		t.Errorf("empty model must leave DefaultModel untouched, got %q", s.DefaultModel)
	}
}

func TestSetDefaultProvider_chains(t *testing.T) {
	s := (&Settings{}).SetDefaultProvider("openai", "gpt-4o")
	if s.DefaultProvider != "openai" {
		t.Errorf("chained SetDefaultProvider must return receiver, got %q", s.DefaultProvider)
	}
}

// ──────────────────────────────────────────────
// Parent-path settings entries survive init
// ──────────────────────────────────────────────

// TestSettingsScaffold_PreservesParentPathEntries asserts that `../private-pi/...`
// skills/prompts entries survive init — nothing strips them anymore (the old

func TestSettingsScaffold_PreservesParentPathEntries(t *testing.T) {
	workdir := t.TempDir()
	s := &Settings{
		Comment: "keep me",
		Skills:  []string{"../private-pi/skills", "bash"},
		Prompts: []string{"../private-pi/prompts", "code-review"},
	}
	if err := s.Save(workdir); err != nil {
		t.Fatal(err)
	}

	// Scaffold is idempotent: existing settings.json is left untouched.
	if err := (&templateSettingsRenderer{source: embeddedFS, templatePath: "embedded/pi/settings.json", dest: func(workdir string) string { return filepath.Join(workdir, ".pi", "settings.json") }}).Scaffold(context.Background(), workdir, TemplateSettingsValues{}); err != nil {
		t.Fatalf("scaffold: %v", err)
	}

	loaded, err := LoadSettings(workdir)
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Contains(loaded.Skills, "../private-pi/skills") {
		t.Errorf("Skills lost parent-path entry: %v", loaded.Skills)
	}
	if !slices.Contains(loaded.Prompts, "../private-pi/prompts") {
		t.Errorf("Prompts lost parent-path entry: %v", loaded.Prompts)
	}
	if loaded.Comment != "keep me" {
		t.Errorf("comment must survive: %q", loaded.Comment)
	}
}

// ──────────────────────────────────────────────
// Scaffold → typed Settings (template.go proof)
// ──────────────────────────────────────────────

func TestSettingsScaffold_outputLoadsAsTypedSettings(t *testing.T) {
	workdir := ScaffoldSettings(t, TemplateSettingsValues{
		Provider: "opencode-go",
		GitName:  "Test User",
		GitEmail: "test@example.com",
		Memory:   "4G",
		CPUs:     "4.0",
	})

	s, err := LoadSettings(workdir)
	if err != nil {
		t.Fatalf("scaffold output must load via LoadSettings: %v", err)
	}
	if s.DefaultProvider != "opencode-go" || s.DefaultModel != "gpt-4o" {
		t.Errorf("provider/model mismatch: %+v", s)
	}
	if s.Docker != (DockerSettings{Memory: "4G", CPUs: "4.0"}) {
		t.Errorf("docker mismatch: %+v", s.Docker)
	}
	if s.GitIdentity != (GitIdentitySettings{Name: "Test User", Email: "test@example.com"}) {
		t.Errorf("gitIdentity mismatch: %+v", s.GitIdentity)
	}
	if !strings.Contains(s.Comment, "Generated by cheasee-pi init") {
		t.Errorf("// comment key must be present in scaffold output, got %q", s.Comment)
	}
	if _, err := os.Stat(filepath.Join(workdir, ".pi", "settings.json") + ".tmp"); !os.IsNotExist(err) {
		t.Error("no .tmp residue after Scaffold")
	}
}

// ──────────────────────────────────────────────
// auth list default section (auth.go)
// ──────────────────────────────────────────────

func TestAuthList_showsSettingsDefault(t *testing.T) {
	testutil.RedirectConfigHome(t)
	seedAuth(t, map[string]string{"openai": FakeAPIKey})

	workdir := t.TempDir()
	if err := (&CheaseeSettings{
		DefaultProvider: "anthropic",
		DefaultModel:    "claude-sonnet-4-20250514",
	}).Save(workdir); err != nil {
		t.Fatal(err)
	}

	withAuthListWorkdir(t, workdir)

	var err error
	stderr := testutil.CaptureStderr(t, func() { err = runAuthListE(&cobra.Command{}, nil) })

	if err != nil {
		t.Fatalf("auth list: %v", err)
	}
	if !strings.Contains(stderr, "Default provider (from cheasee-settings.json): anthropic") {
		t.Errorf("missing default provider section, got: %q", stderr)
	}
	if !strings.Contains(stderr, "Default model: claude-sonnet-4-20250514") {
		t.Errorf("missing default model line, got: %q", stderr)
	}
}

func TestAuthList_missingSettingsNoDefaultSection(t *testing.T) {
	testutil.RedirectConfigHome(t)
	seedAuth(t, map[string]string{"openai": FakeAPIKey})

	withAuthListWorkdir(t, t.TempDir()) // no cheasee-settings.json

	var err error
	stderr := testutil.CaptureStderr(t, func() { err = runAuthListE(&cobra.Command{}, nil) })

	if err != nil {
		t.Fatalf("auth list: %v", err)
	}
	if strings.Contains(stderr, "Default provider") {
		t.Errorf("missing settings must not print a default section, got: %q", stderr)
	}
}

// ──────────────────────────────────────────────
