package main

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/SchneiderDaniel/cheasee-pi/cmd/cheasee-pi/testutil"
)

// fullSchema is the canonical scaffold output with the new /opt/cheasee-pi
// resource paths and the extended schema (extensions/theme/sessionDir).
var fullSchema = &Settings{
	Comment:         "Generated by cheasee-pi init. Edit this file to configure your pi environment.",
	DefaultProvider: "opencode-go",
	DefaultModel:    "gpt-4o",
	Docker:          DockerSettings{Memory: "4G", CPUs: "4.0"},
	GitIdentity:     GitIdentitySettings{Name: "Test User", Email: "test@example.com"},
	Skills:          []string{"/opt/cheasee-pi/.pi/skills", "bash", "web"},
	Prompts:         []string{"/opt/cheasee-pi/.pi/prompts", "code-review"},
	Extensions:      []string{"/opt/cheasee-pi/.pi/extensions"},
	Theme:           "cheasee-pi",
	SessionDir:      ".pi/sessions",
}

// ──────────────────────────────────────────────
// Save → Load round-trip (adapter)
// ──────────────────────────────────────────────

func TestSettingsRoundTrip_fullSchemaSurvives(t *testing.T) {
	workdir := t.TempDir()
	if err := fullSchema.Save(workdir); err != nil {
		t.Fatalf("Save failed: %v", err)
	}

	loaded, err := LoadSettings(workdir)
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}

	if loaded.Comment != fullSchema.Comment {
		t.Errorf("Comment = %q, want %q", loaded.Comment, fullSchema.Comment)
	}
	if loaded.DefaultProvider != fullSchema.DefaultProvider {
		t.Errorf("DefaultProvider = %q, want %q", loaded.DefaultProvider, fullSchema.DefaultProvider)
	}
	if loaded.DefaultModel != fullSchema.DefaultModel {
		t.Errorf("DefaultModel = %q, want %q", loaded.DefaultModel, fullSchema.DefaultModel)
	}
	if loaded.Docker != fullSchema.Docker {
		t.Errorf("Docker = %+v, want %+v", loaded.Docker, fullSchema.Docker)
	}
	if loaded.GitIdentity != fullSchema.GitIdentity {
		t.Errorf("GitIdentity = %+v, want %+v", loaded.GitIdentity, fullSchema.GitIdentity)
	}
	if len(loaded.Skills) != len(fullSchema.Skills) || loaded.Skills[0] != fullSchema.Skills[0] {
		t.Errorf("Skills = %v, want %v", loaded.Skills, fullSchema.Skills)
	}
	if len(loaded.Prompts) != len(fullSchema.Prompts) || loaded.Prompts[0] != fullSchema.Prompts[0] {
		t.Errorf("Prompts = %v, want %v", loaded.Prompts, fullSchema.Prompts)
	}
	if len(loaded.Extensions) != len(fullSchema.Extensions) || loaded.Extensions[0] != fullSchema.Extensions[0] {
		t.Errorf("Extensions = %v, want %v", loaded.Extensions, fullSchema.Extensions)
	}
	if loaded.Theme != fullSchema.Theme {
		t.Errorf("Theme = %q, want %q", loaded.Theme, fullSchema.Theme)
	}
	if loaded.SessionDir != fullSchema.SessionDir {
		t.Errorf("SessionDir = %q, want %q", loaded.SessionDir, fullSchema.SessionDir)
	}
}

func TestSettingsSave_byteStable(t *testing.T) {
	workdir := t.TempDir()
	if err := fullSchema.Save(workdir); err != nil {
		t.Fatalf("first Save failed: %v", err)
	}
	first, err := os.ReadFile(filepath.Join(workdir, ".pi", "settings.json"))
	if err != nil {
		t.Fatal(err)
	}

	if err := fullSchema.Save(workdir); err != nil {
		t.Fatalf("second Save failed: %v", err)
	}
	second, err := os.ReadFile(filepath.Join(workdir, ".pi", "settings.json"))
	if err != nil {
		t.Fatal(err)
	}

	if string(first) != string(second) {
		t.Errorf("repeated Save must be byte-identical:\nfirst:  %q\nsecond: %q", first, second)
	}
}

func TestSettingsSave_htmlSafe(t *testing.T) {
	s := &Settings{
		Skills:  []string{"use <b>bold</b> & <i>italic</i> in output"},
		Prompts: []string{"a > b"},
	}
	workdir := t.TempDir()
	if err := s.Save(workdir); err != nil {
		t.Fatalf("Save failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(workdir, ".pi", "settings.json"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), `\u003c`) || strings.Contains(string(data), `\u003e`) || strings.Contains(string(data), `\u0026`) {
		t.Errorf("Save HTML-escaped <>&: %s", data)
	}
	if !strings.Contains(string(data), "<b>bold</b>") {
		t.Errorf("skills entry must survive byte-identical, got: %s", data)
	}
}

func TestSettingsSave_createsParentDirsNoTmpResidue(t *testing.T) {
	workdir := t.TempDir()
	if err := fullSchema.Save(workdir); err != nil {
		t.Fatalf("Save failed: %v", err)
	}

	path := filepath.Join(workdir, ".pi", "settings.json")
	fi, err := os.Stat(path)
	if err != nil {
		t.Fatalf("settings.json missing: %v", err)
	}
	if fi.Mode().Perm() != 0644 {
		t.Errorf("settings.json mode = %v, want 0644", fi.Mode().Perm())
	}
	if _, err := os.Stat(path + ".tmp"); !os.IsNotExist(err) {
		t.Error("no .tmp file should remain after Save")
	}
}

func TestSettingsSave_unwritableDirErrorsNoPartialFile(t *testing.T) {
	workdir := t.TempDir()
	if err := os.Mkdir(filepath.Join(workdir, ".pi"), 0555); err != nil {
		t.Fatal(err)
	}
	defer os.Chmod(filepath.Join(workdir, ".pi"), 0755)

	err := fullSchema.Save(workdir)
	if err == nil {
		t.Fatal("expected error writing into read-only .pi dir, got nil")
	}
	if _, statErr := os.Stat(filepath.Join(workdir, ".pi", "settings.json")); !os.IsNotExist(statErr) {
		t.Error("target file must be absent after failed Save (no partial write)")
	}
}

// ──────────────────────────────────────────────
// Load failure modes (adapter)
// ──────────────────────────────────────────────

func TestLoadSettings_missingFile(t *testing.T) {
	workdir := t.TempDir()
	_, err := LoadSettings(workdir)
	if !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("missing settings.json: want os.ErrNotExist, got %v", err)
	}
}

func TestLoadSettings_missingPiDir(t *testing.T) {
	workdir := t.TempDir()
	_, err := LoadSettings(workdir)
	if !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("missing .pi dir: want os.ErrNotExist, got %v", err)
	}
}

func TestLoadSettings_corruptJSON(t *testing.T) {
	workdir := t.TempDir()
	testutil.WriteSettingsFile(t, workdir, "{invalid json")
	if _, err := LoadSettings(workdir); err == nil {
		t.Fatal("expected error for corrupt JSON, got nil")
	}
}

func TestLoadSettings_typeMismatch(t *testing.T) {
	workdir := t.TempDir()
	testutil.WriteSettingsFile(t, workdir, `{"docker": {"memory": 4096}}`)
	if _, err := LoadSettings(workdir); err == nil {
		t.Fatal("expected error for docker.memory as number, got nil")
	}
}

func TestLoadSettings_nonObjectJSON(t *testing.T) {
	workdir := t.TempDir()
	testutil.WriteSettingsFile(t, workdir, `[1,2]`)
	if _, err := LoadSettings(workdir); err == nil {
		t.Fatal("expected error for non-object JSON, got nil")
	}
}

func TestLoadSettings_nullJSON(t *testing.T) {
	// The JSON literal null unmarshals cleanly into both the typed struct and
	// the raw map (leaving the map nil), so it must be rejected explicitly:
	// a null .pi/settings.json is a hard error, never an empty schema that a
	// subsequent Save silently overwrites.
	workdir := t.TempDir()
	testutil.WriteSettingsFile(t, workdir, `null`)
	if _, err := LoadSettings(workdir); err == nil {
		t.Fatal("expected error for null JSON, got nil")
	}
}

func TestLoadSettings_emptyObject(t *testing.T) {
	workdir := t.TempDir()
	testutil.WriteSettingsFile(t, workdir, `{}`)
	s, err := LoadSettings(workdir)
	if err != nil {
		t.Fatalf("empty {} must load without error, got %v", err)
	}
	if s.DefaultProvider != "" || s.Docker.Memory != "" {
		t.Errorf("empty {} must yield zero-value Settings, got %+v", s)
	}
}

func TestLoadSettings_preservesUnknownAndCaseVariantKeys(t *testing.T) {
	workdir := t.TempDir()
	// encoding/json accepts case-variant keys. Preserve all other pi and
	// extension settings when cheasee-pi later updates its provider fields.
	testutil.WriteSettingsFile(t, workdir, `{"DefaultProvider":"openai","futureKey":42,"supervisor":{"repo":"owner/repo"}}`)
	s, err := LoadSettings(workdir)
	if err != nil {
		t.Fatalf("case-variant/unknown keys must load, got %v", err)
	}
	if s.DefaultProvider != "openai" {
		t.Errorf("DefaultProvider = %q, want openai (case-insensitive key match)", s.DefaultProvider)
	}
	if err := s.Save(workdir); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(filepath.Join(workdir, ".pi", "settings.json"))
	if !strings.Contains(string(data), "futureKey") || !strings.Contains(string(data), "supervisor") || !strings.Contains(string(data), `"repo": "owner/repo"`) {
		t.Errorf("Save lost unknown settings: %s", data)
	}
}
