package main

import (
	"context"
	"errors"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

// fullSchema is the canonical scaffold output with skills/prompts added.
var fullSchema = &Settings{
	Comment:         "Generated by cheasee-pi init. Edit this file to configure your pi environment.",
	DefaultProvider: "opencode-go",
	DefaultModel:    "gpt-4o",
	Docker:          DockerSettings{Memory: "4G", CPUs: "4.0"},
	GitIdentity:     GitIdentitySettings{Name: "Test User", Email: "test@example.com"},
	Skills:          []string{"../private-pi/skills", "bash", "web"},
	Prompts:         []string{"../private-pi/prompts", "code-review"},
}

// ──────────────────────────────────────────────
// SetDefaultProvider (entity)
// ──────────────────────────────────────────────

func TestSetDefaultProvider_setsBothFields(t *testing.T) {
	s := &Settings{}
	s.SetDefaultProvider("openai", "gpt-4o")
	if s.DefaultProvider != "openai" {
		t.Errorf("DefaultProvider = %q, want openai", s.DefaultProvider)
	}
	if s.DefaultModel != "gpt-4o" {
		t.Errorf("DefaultModel = %q, want gpt-4o", s.DefaultModel)
	}
}

func TestSetDefaultProvider_emptyModelKeepsExisting(t *testing.T) {
	s := &Settings{DefaultModel: "gpt-4o-mini"}
	s.SetDefaultProvider("openai", "")
	if s.DefaultProvider != "openai" {
		t.Errorf("DefaultProvider = %q, want openai", s.DefaultProvider)
	}
	if s.DefaultModel != "gpt-4o-mini" {
		t.Errorf("empty model must leave DefaultModel untouched, got %q", s.DefaultModel)
	}
}

func TestSetDefaultProvider_chains(t *testing.T) {
	s := (&Settings{}).SetDefaultProvider("openai", "gpt-4o")
	if s.DefaultProvider != "openai" {
		t.Errorf("chained SetDefaultProvider must return receiver, got %q", s.DefaultProvider)
	}
}

// ──────────────────────────────────────────────
// Save → Load round-trip (adapter)
// ──────────────────────────────────────────────

func TestSettingsRoundTrip_fullSchemaSurvives(t *testing.T) {
	workdir := t.TempDir()
	if err := fullSchema.Save(workdir); err != nil {
		t.Fatalf("Save failed: %v", err)
	}

	loaded, err := LoadSettings(workdir)
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}

	if loaded.Comment != fullSchema.Comment {
		t.Errorf("Comment = %q, want %q", loaded.Comment, fullSchema.Comment)
	}
	if loaded.DefaultProvider != fullSchema.DefaultProvider {
		t.Errorf("DefaultProvider = %q, want %q", loaded.DefaultProvider, fullSchema.DefaultProvider)
	}
	if loaded.DefaultModel != fullSchema.DefaultModel {
		t.Errorf("DefaultModel = %q, want %q", loaded.DefaultModel, fullSchema.DefaultModel)
	}
	if loaded.Docker != fullSchema.Docker {
		t.Errorf("Docker = %+v, want %+v", loaded.Docker, fullSchema.Docker)
	}
	if loaded.GitIdentity != fullSchema.GitIdentity {
		t.Errorf("GitIdentity = %+v, want %+v", loaded.GitIdentity, fullSchema.GitIdentity)
	}
	if len(loaded.Skills) != len(fullSchema.Skills) || loaded.Skills[0] != fullSchema.Skills[0] {
		t.Errorf("Skills = %v, want %v", loaded.Skills, fullSchema.Skills)
	}
	if len(loaded.Prompts) != len(fullSchema.Prompts) || loaded.Prompts[0] != fullSchema.Prompts[0] {
		t.Errorf("Prompts = %v, want %v", loaded.Prompts, fullSchema.Prompts)
	}
}

func TestSettingsSave_byteStable(t *testing.T) {
	workdir := t.TempDir()
	if err := fullSchema.Save(workdir); err != nil {
		t.Fatalf("first Save failed: %v", err)
	}
	first, err := os.ReadFile(filepath.Join(workdir, ".pi", "settings.json"))
	if err != nil {
		t.Fatal(err)
	}

	if err := fullSchema.Save(workdir); err != nil {
		t.Fatalf("second Save failed: %v", err)
	}
	second, err := os.ReadFile(filepath.Join(workdir, ".pi", "settings.json"))
	if err != nil {
		t.Fatal(err)
	}

	if string(first) != string(second) {
		t.Errorf("repeated Save must be byte-identical:\nfirst:  %q\nsecond: %q", first, second)
	}
}

func TestSettingsSave_htmlSafe(t *testing.T) {
	s := &Settings{
		Skills:  []string{"use <b>bold</b> & <i>italic</i> in output"},
		Prompts: []string{"a > b"},
	}
	workdir := t.TempDir()
	if err := s.Save(workdir); err != nil {
		t.Fatalf("Save failed: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(workdir, ".pi", "settings.json"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), `\u003c`) || strings.Contains(string(data), `\u003e`) || strings.Contains(string(data), `\u0026`) {
		t.Errorf("Save HTML-escaped <>&: %s", data)
	}
	if !strings.Contains(string(data), "<b>bold</b>") {
		t.Errorf("skills entry must survive byte-identical, got: %s", data)
	}
}

func TestSettingsSave_createsParentDirsNoTmpResidue(t *testing.T) {
	workdir := t.TempDir()
	if err := fullSchema.Save(workdir); err != nil {
		t.Fatalf("Save failed: %v", err)
	}

	path := filepath.Join(workdir, ".pi", "settings.json")
	fi, err := os.Stat(path)
	if err != nil {
		t.Fatalf("settings.json missing: %v", err)
	}
	if fi.Mode().Perm() != 0644 {
		t.Errorf("settings.json mode = %v, want 0644", fi.Mode().Perm())
	}
	if _, err := os.Stat(path + ".tmp"); !os.IsNotExist(err) {
		t.Error("no .tmp file should remain after Save")
	}
}

func TestSettingsSave_unwritableDirErrorsNoPartialFile(t *testing.T) {
	workdir := t.TempDir()
	if err := os.Mkdir(filepath.Join(workdir, ".pi"), 0555); err != nil {
		t.Fatal(err)
	}
	defer os.Chmod(filepath.Join(workdir, ".pi"), 0755)

	err := fullSchema.Save(workdir)
	if err == nil {
		t.Fatal("expected error writing into read-only .pi dir, got nil")
	}
	if _, statErr := os.Stat(filepath.Join(workdir, ".pi", "settings.json")); !os.IsNotExist(statErr) {
		t.Error("target file must be absent after failed Save (no partial write)")
	}
}

// ──────────────────────────────────────────────
// Load failure modes (adapter)
// ──────────────────────────────────────────────

func TestLoadSettings_missingFile(t *testing.T) {
	workdir := t.TempDir()
	_, err := LoadSettings(workdir)
	if !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("missing settings.json: want os.ErrNotExist, got %v", err)
	}
}

func TestLoadSettings_missingPiDir(t *testing.T) {
	workdir := t.TempDir()
	_, err := LoadSettings(workdir)
	if !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("missing .pi dir: want os.ErrNotExist, got %v", err)
	}
}

func TestLoadSettings_corruptJSON(t *testing.T) {
	workdir := t.TempDir()
	writeSettingsFile(t, workdir, "{invalid json")
	if _, err := LoadSettings(workdir); err == nil {
		t.Fatal("expected error for corrupt JSON, got nil")
	}
}

func TestLoadSettings_typeMismatch(t *testing.T) {
	workdir := t.TempDir()
	writeSettingsFile(t, workdir, `{"docker": {"memory": 4096}}`)
	if _, err := LoadSettings(workdir); err == nil {
		t.Fatal("expected error for docker.memory as number, got nil")
	}
}

func TestLoadSettings_nonObjectJSON(t *testing.T) {
	workdir := t.TempDir()
	writeSettingsFile(t, workdir, `[1,2]`)
	if _, err := LoadSettings(workdir); err == nil {
		t.Fatal("expected error for non-object JSON, got nil")
	}
}

func TestLoadSettings_emptyObject(t *testing.T) {
	workdir := t.TempDir()
	writeSettingsFile(t, workdir, `{}`)
	s, err := LoadSettings(workdir)
	if err != nil {
		t.Fatalf("empty {} must load without error, got %v", err)
	}
	if s.DefaultProvider != "" || s.Docker.Memory != "" {
		t.Errorf("empty {} must yield zero-value Settings, got %+v", s)
	}
}

func TestLoadSettings_lenientUnknownAndCaseVariantKeys(t *testing.T) {
	workdir := t.TempDir()
	// Unknown keys and case-variant keys were accepted by the old map reads
	// (encoding/json matches keys case-insensitively) — v1 compat.
	writeSettingsFile(t, workdir, `{"DefaultProvider": "openai", "futureKey": 42}`)
	s, err := LoadSettings(workdir)
	if err != nil {
		t.Fatalf("case-variant/unknown keys must load, got %v", err)
	}
	if s.DefaultProvider != "openai" {
		t.Errorf("DefaultProvider = %q, want openai (case-insensitive key match)", s.DefaultProvider)
	}

	// But a typed Save drops undeclared keys (documented trade-off).
	if err := s.Save(workdir); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(filepath.Join(workdir, ".pi", "settings.json"))
	if strings.Contains(string(data), "futureKey") {
		t.Errorf("Save must drop undeclared keys, got: %s", data)
	}
}

// ──────────────────────────────────────────────
// memoryLimitEnv (up/build shared reader)
// ──────────────────────────────────────────────

func TestMemoryLimitEnv_present(t *testing.T) {
	workdir := t.TempDir()
	writeSettingsFile(t, workdir, `{"docker": {"memory": "4G"}}`)
	env, ok := memoryLimitEnv(workdir)
	if !ok {
		t.Fatal("expected ok=true for docker.memory=4G")
	}
	if env != "CHEASEEPI_MEMORY=4G" {
		t.Errorf("env = %q, want CHEASEEPI_MEMORY=4G", env)
	}
}

func TestMemoryLimitEnv_missingFileSilent(t *testing.T) {
	workdir := t.TempDir()
	env, ok := memoryLimitEnv(workdir)
	if ok || env != "" {
		t.Errorf("missing file: want (\"\", false), got (%q, %v)", env, ok)
	}
}

func TestMemoryLimitEnv_corruptWarns(t *testing.T) {
	workdir := t.TempDir()
	writeSettingsFile(t, workdir, "{nope")

	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	old := os.Stderr
	os.Stderr = w
	env, ok := memoryLimitEnv(workdir)
	w.Close()
	os.Stderr = old
	stderr, _ := io.ReadAll(r)

	if ok || env != "" {
		t.Errorf("corrupt JSON: want (\"\", false), got (%q, %v)", env, ok)
	}
	if !strings.Contains(string(stderr), "settings.json") {
		t.Errorf("corrupt JSON must warn on stderr, got: %q", stderr)
	}
}

func TestMemoryLimitEnv_emptyMemory(t *testing.T) {
	workdir := t.TempDir()
	writeSettingsFile(t, workdir, `{"docker": {"memory": ""}}`)
	if env, ok := memoryLimitEnv(workdir); ok || env != "" {
		t.Errorf("empty memory: want (\"\", false), got (%q, %v)", env, ok)
	}
}

func TestMemoryLimitEnv_noDockerSection(t *testing.T) {
	workdir := t.TempDir()
	writeSettingsFile(t, workdir, `{"defaultProvider": "openai"}`)
	if env, ok := memoryLimitEnv(workdir); ok || env != "" {
		t.Errorf("no docker section: want (\"\", false), got (%q, %v)", env, ok)
	}
}

// ──────────────────────────────────────────────
// SettingsWriter (provider.go)
// ──────────────────────────────────────────────

func TestSettingsWriter_preservesSchema(t *testing.T) {
	workdir := t.TempDir()
	if err := fullSchema.Save(workdir); err != nil {
		t.Fatal(err)
	}

	sw := &SettingsWriter{Workdir: workdir}
	if err := sw.WriteDefaultProvider("anthropic", "claude-sonnet-4-20250514"); err != nil {
		t.Fatalf("WriteDefaultProvider: %v", err)
	}

	s, err := LoadSettings(workdir)
	if err != nil {
		t.Fatal(err)
	}
	if s.DefaultProvider != "anthropic" || s.DefaultModel != "claude-sonnet-4-20250514" {
		t.Errorf("provider/model not updated: %+v", s)
	}
	if s.Comment != fullSchema.Comment {
		t.Errorf("comment key must survive: %q", s.Comment)
	}
	if s.Docker != fullSchema.Docker || s.GitIdentity != fullSchema.GitIdentity {
		t.Errorf("docker/gitIdentity must survive: %+v", s)
	}
	if len(s.Skills) != len(fullSchema.Skills) {
		t.Errorf("skills must survive: %v", s.Skills)
	}
}

func TestSettingsWriter_emptyModelKeepsExisting(t *testing.T) {
	workdir := t.TempDir()
	if err := fullSchema.Save(workdir); err != nil {
		t.Fatal(err)
	}

	sw := &SettingsWriter{Workdir: workdir}
	if err := sw.WriteDefaultProvider("openai", ""); err != nil {
		t.Fatalf("WriteDefaultProvider: %v", err)
	}

	s, _ := LoadSettings(workdir)
	if s.DefaultModel != "gpt-4o" {
		t.Errorf("empty model must keep existing defaultModel, got %q", s.DefaultModel)
	}
}

func TestSettingsWriter_missingPISettingsSkipped(t *testing.T) {
	workdir := t.TempDir() // no .pi/settings.json
	sw := &SettingsWriter{Workdir: workdir}
	if err := sw.WriteDefaultProvider("openai", "gpt-4o"); err != nil {
		t.Fatalf("missing .pi/settings.json must be skipped, got %v", err)
	}
	if _, err := os.Stat(filepath.Join(workdir, ".pi", "settings.json")); !os.IsNotExist(err) {
		t.Error("missing file must not be created")
	}
}

func TestSettingsWriter_corruptPISettingsErrors(t *testing.T) {
	workdir := t.TempDir()
	writeSettingsFile(t, workdir, "{nope")
	sw := &SettingsWriter{Workdir: workdir}
	err := sw.WriteDefaultProvider("openai", "gpt-4o")
	if err == nil || !strings.Contains(err.Error(), ".pi/settings.json") {
		t.Fatalf("expected wrapped error mentioning .pi/settings.json, got %v", err)
	}
}

func TestSettingsWriter_agentPathCreateIfMissing(t *testing.T) {
	workdir := t.TempDir()
	sw := &SettingsWriter{Workdir: workdir}
	if err := sw.WriteDefaultProvider("openai", "gpt-4o"); err != nil {
		t.Fatalf("WriteDefaultProvider: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(workdir, ".pi", "agent", "settings.json"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), "defaultModel") {
		t.Errorf("agent file should be created with defaultProvider only, got: %s", data)
	}
	if !strings.Contains(string(data), `"defaultProvider": "openai"`) {
		t.Errorf("agent file missing defaultProvider, got: %s", data)
	}
}

func TestSettingsWriter_agentPathUpdatesExisting(t *testing.T) {
	workdir := t.TempDir()
	agentPath := filepath.Join(workdir, ".pi", "agent", "settings.json")
	os.MkdirAll(filepath.Dir(agentPath), 0755)
	os.WriteFile(agentPath, []byte(`{"defaultProvider": "openai", "defaultModel": "gpt-4o"}`), 0644)

	sw := &SettingsWriter{Workdir: workdir}
	if err := sw.WriteDefaultProvider("anthropic", "claude-sonnet-4-20250514"); err != nil {
		t.Fatalf("WriteDefaultProvider: %v", err)
	}

	data, _ := os.ReadFile(agentPath)
	if !strings.Contains(string(data), `"defaultProvider": "anthropic"`) {
		t.Errorf("agent defaultProvider not updated: %s", data)
	}
	if !strings.Contains(string(data), `"defaultModel": "gpt-4o"`) {
		t.Errorf("agent defaultModel must be preserved: %s", data)
	}
}

// ──────────────────────────────────────────────
// removeSubmoduleSettings (init_submodule.go)
// ──────────────────────────────────────────────

func TestRemoveSubmoduleSettings_filtersParentPaths(t *testing.T) {
	workdir := t.TempDir()
	s := &Settings{
		Comment: "keep me",
		Skills:  []string{"../private-pi/skills", "bash", "..\\win-style"},
		Prompts: []string{"../private-pi/prompts", "code-review"},
	}
	if err := s.Save(workdir); err != nil {
		t.Fatal(err)
	}

	if err := removeSubmoduleSettings(workdir); err != nil {
		t.Fatalf("removeSubmoduleSettings: %v", err)
	}

	loaded, err := LoadSettings(workdir)
	if err != nil {
		t.Fatal(err)
	}
	if len(loaded.Skills) != 1 || loaded.Skills[0] != "bash" {
		t.Errorf("Skills = %v, want [bash]", loaded.Skills)
	}
	if len(loaded.Prompts) != 1 || loaded.Prompts[0] != "code-review" {
		t.Errorf("Prompts = %v, want [code-review]", loaded.Prompts)
	}
	if loaded.Comment != "keep me" {
		t.Errorf("comment must survive: %q", loaded.Comment)
	}
	if _, err := os.Stat(filepath.Join(workdir, ".pi", "settings.json") + ".tmp"); !os.IsNotExist(err) {
		t.Error("no .tmp residue after submodule cleanup")
	}
}

func TestRemoveSubmoduleSettings_noParentPathsNoWrite(t *testing.T) {
	workdir := t.TempDir()
	s := &Settings{Comment: "keep", Skills: []string{"bash", "web"}}
	if err := s.Save(workdir); err != nil {
		t.Fatal(err)
	}
	before, _ := os.ReadFile(filepath.Join(workdir, ".pi", "settings.json"))

	if err := removeSubmoduleSettings(workdir); err != nil {
		t.Fatalf("removeSubmoduleSettings: %v", err)
	}

	after, _ := os.ReadFile(filepath.Join(workdir, ".pi", "settings.json"))
	if string(before) != string(after) {
		t.Errorf("no parent paths: file must be untouched\nbefore: %s\nafter:  %s", before, after)
	}
}

func TestRemoveSubmoduleSettings_missingFileNil(t *testing.T) {
	workdir := t.TempDir()
	if err := removeSubmoduleSettings(workdir); err != nil {
		t.Fatalf("missing file must return nil, got %v", err)
	}
}

func TestRemoveSubmoduleSettings_corruptFileErrors(t *testing.T) {
	workdir := t.TempDir()
	writeSettingsFile(t, workdir, "{nope")
	if err := removeSubmoduleSettings(workdir); err == nil {
		t.Fatal("expected error for corrupt settings, got nil")
	}
}

// ──────────────────────────────────────────────
// applyMemoryLimit (up/build command path)
// ──────────────────────────────────────────────

func TestApplyMemoryLimit_setsEnvAndAnnounces(t *testing.T) {
	workdir := t.TempDir()
	writeSettingsFile(t, workdir, `{"docker": {"memory": "4G"}}`)

	cmd := exec.Command("echo") // never run
	r, w, _ := os.Pipe()
	old := os.Stderr
	os.Stderr = w
	applyMemoryLimit(cmd, workdir)
	w.Close()
	os.Stderr = old
	stderr, _ := io.ReadAll(r)

	if !slices.Contains(cmd.Env, "CHEASEEPI_MEMORY=4G") {
		t.Errorf("cmd.Env missing CHEASEEPI_MEMORY=4G, got %v", cmd.Env)
	}
	if !strings.Contains(string(stderr), "Using memory limit 4G from settings.json") {
		t.Errorf("expected announcement on stderr, got: %q", stderr)
	}
}

func TestApplyMemoryLimit_noLimitNoEnv(t *testing.T) {
	cmd := exec.Command("echo")
	before := cmd.Env
	applyMemoryLimit(cmd, t.TempDir()) // no .pi/settings.json
	if !slices.Equal(cmd.Env, before) {
		t.Errorf("cmd.Env must be untouched without a limit, got %v", cmd.Env)
	}
}

// ──────────────────────────────────────────────
// Scaffold → typed Settings (template.go proof)
// ──────────────────────────────────────────────

func TestSettingsScaffold_outputLoadsAsTypedSettings(t *testing.T) {
	scaffold := NewSettingsScaffold()
	workdir := t.TempDir()

	vals := TemplateSettingsValues{
		Provider: "opencode-go",
		GitName:  "Test User",
		GitEmail: "test@example.com",
		Memory:   "4G",
		CPUs:     "4.0",
	}
	if err := scaffold.Scaffold(context.Background(), workdir, vals); err != nil {
		t.Fatalf("Scaffold failed: %v", err)
	}

	s, err := LoadSettings(workdir)
	if err != nil {
		t.Fatalf("scaffold output must load via LoadSettings: %v", err)
	}
	if s.DefaultProvider != "opencode-go" || s.DefaultModel != "gpt-4o" {
		t.Errorf("provider/model mismatch: %+v", s)
	}
	if s.Docker != (DockerSettings{Memory: "4G", CPUs: "4.0"}) {
		t.Errorf("docker mismatch: %+v", s.Docker)
	}
	if s.GitIdentity != (GitIdentitySettings{Name: "Test User", Email: "test@example.com"}) {
		t.Errorf("gitIdentity mismatch: %+v", s.GitIdentity)
	}
	if !strings.Contains(s.Comment, "Generated by cheasee-pi init") {
		t.Errorf("// comment key must be present in scaffold output, got %q", s.Comment)
	}
	if _, err := os.Stat(filepath.Join(workdir, ".pi", "settings.json") + ".tmp"); !os.IsNotExist(err) {
		t.Error("no .tmp residue after Scaffold")
	}
}

// ──────────────────────────────────────────────
// auth list default section (auth.go)
// ──────────────────────────────────────────────

func TestAuthList_showsSettingsDefault(t *testing.T) {
	xdg := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", xdg)
	cfg := &fileRepository{}
	if err := cfg.AddProvider(context.Background(), "openai", "sk-openai-1"); err != nil {
		t.Fatal(err)
	}

	workdir := t.TempDir()
	if err := (&Settings{
		DefaultProvider: "anthropic",
		DefaultModel:    "claude-sonnet-4-20250514",
	}).Save(workdir); err != nil {
		t.Fatal(err)
	}

	saved := authListWorkdir
	authListWorkdir = workdir
	defer func() { authListWorkdir = saved }()

	r, w, _ := os.Pipe()
	old := os.Stderr
	os.Stderr = w
	err := runAuthListE(&cobra.Command{}, nil)
	w.Close()
	os.Stderr = old
	stderr, _ := io.ReadAll(r)

	if err != nil {
		t.Fatalf("auth list: %v", err)
	}
	if !strings.Contains(string(stderr), "Default provider (from .pi/settings.json): anthropic") {
		t.Errorf("missing default provider section, got: %q", stderr)
	}
	if !strings.Contains(string(stderr), "Default model: claude-sonnet-4-20250514") {
		t.Errorf("missing default model line, got: %q", stderr)
	}
}

func TestAuthList_missingSettingsNoDefaultSection(t *testing.T) {
	xdg := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", xdg)
	cfg := &fileRepository{}
	if err := cfg.AddProvider(context.Background(), "openai", "sk-openai-1"); err != nil {
		t.Fatal(err)
	}

	saved := authListWorkdir
	authListWorkdir = t.TempDir() // no .pi/settings.json
	defer func() { authListWorkdir = saved }()

	r, w, _ := os.Pipe()
	old := os.Stderr
	os.Stderr = w
	err := runAuthListE(&cobra.Command{}, nil)
	w.Close()
	os.Stderr = old
	stderr, _ := io.ReadAll(r)

	if err != nil {
		t.Fatalf("auth list: %v", err)
	}
	if strings.Contains(string(stderr), "Default provider") {
		t.Errorf("missing settings must not print a default section, got: %q", stderr)
	}
}

// ──────────────────────────────────────────────
// helpers
// ──────────────────────────────────────────────

func writeSettingsFile(t *testing.T, workdir, content string) {
	t.Helper()
	path := filepath.Join(workdir, ".pi", "settings.json")
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}
