package main

import (
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/SchneiderDaniel/cheasee-pi/cmd/cheasee-pi/testutil"
)

// ──────────────────────────────────────────────
// CheaseeSettings schema (dedicated settings file)
// ──────────────────────────────────────────────

// fullCheaseeSchema is the canonical cheasee-settings.json content.
var fullCheaseeSchema = &CheaseeSettings{
	Comment:         "Generated by cheasee-pi init. Edit this file to configure your cheasee-pi environment.",
	DefaultProvider: "opencode-go",
	Docker:          DockerSettings{Memory: "4G", CPUs: "4.0"},
	GitIdentity:     GitIdentitySettings{Name: "Test User", Email: "test@example.com"},
	OAuth:           OAuthSettings{ClientID: "test-client"},
	Repository:      &RepositorySettings{URL: "https://github.com/owner/repo.git", User: "octocat"},
}

func TestCheaseeSettings_roundTrip(t *testing.T) {
	workdir := t.TempDir()
	if err := fullCheaseeSchema.Save(workdir); err != nil {
		t.Fatalf("Save failed: %v", err)
	}

	loaded, err := LoadCheaseeSettings(workdir)
	if err != nil {
		t.Fatalf("Load failed: %v", err)
	}
	// Repository is a pointer (omitempty for the legacy no-github output), so
	// compare values rather than struct equality.
	if !reflect.DeepEqual(loaded, fullCheaseeSchema) {
		t.Errorf("round-trip mismatch:\n got %+v\nwant %+v", loaded, fullCheaseeSchema)
	}
}

func TestCheaseeSettings_nilRepositoryOmitsSection(t *testing.T) {
	// Legacy/no-github output: {} loads with nil Repository, and a typed Save
	// must not emit a repository key (omitempty, section-free legacy output).
	workdir := t.TempDir()
	testutil.WriteCheaseeSettingsFile(t, workdir, `{}`)
	s, err := LoadCheaseeSettings(workdir)
	if err != nil {
		t.Fatal(err)
	}
	if s.Repository != nil {
		t.Fatalf("empty {} must load with nil Repository, got %+v", s.Repository)
	}
	if err := s.Save(workdir); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(cheaseeSettingsPath(workdir))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), "repository") {
		t.Errorf("Save of nil Repository must not emit a repository key, got: %s", data)
	}
}

func TestCheaseeSettings_saveByteStable(t *testing.T) {
	workdir := t.TempDir()
	if err := fullCheaseeSchema.Save(workdir); err != nil {
		t.Fatalf("first Save failed: %v", err)
	}
	first, err := os.ReadFile(cheaseeSettingsPath(workdir))
	if err != nil {
		t.Fatal(err)
	}
	if err := fullCheaseeSchema.Save(workdir); err != nil {
		t.Fatalf("second Save failed: %v", err)
	}
	second, err := os.ReadFile(cheaseeSettingsPath(workdir))
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Errorf("repeated Save must be byte-identical:\nfirst:  %q\nsecond: %q", first, second)
	}
}

func TestLoadCheaseeSettings_failureModes(t *testing.T) {
	t.Run("missing file", func(t *testing.T) {
		_, err := LoadCheaseeSettings(t.TempDir())
		if !errors.Is(err, os.ErrNotExist) {
			t.Fatalf("missing file: want os.ErrNotExist, got %v", err)
		}
	})
	t.Run("corrupt JSON", func(t *testing.T) {
		workdir := t.TempDir()
		testutil.WriteCheaseeSettingsFile(t, workdir, "{invalid")
		if _, err := LoadCheaseeSettings(workdir); err == nil {
			t.Fatal("corrupt JSON must be a hard error")
		}
	})
	t.Run("type mismatch", func(t *testing.T) {
		workdir := t.TempDir()
		testutil.WriteCheaseeSettingsFile(t, workdir, `{"docker": {"memory": 4096}}`)
		if _, err := LoadCheaseeSettings(workdir); err == nil {
			t.Fatal("type mismatch must be a hard error")
		}
	})
	t.Run("non-object", func(t *testing.T) {
		workdir := t.TempDir()
		testutil.WriteCheaseeSettingsFile(t, workdir, `[1,2]`)
		if _, err := LoadCheaseeSettings(workdir); err == nil {
			t.Fatal("non-object JSON must be a hard error")
		}
	})
	t.Run("null JSON", func(t *testing.T) {
		// null unmarshals cleanly into both the typed struct and the raw map
		// (leaving the map nil) — it must be a hard error, not an empty schema
		// a later Save would silently overwrite.
		workdir := t.TempDir()
		testutil.WriteCheaseeSettingsFile(t, workdir, `null`)
		if _, err := LoadCheaseeSettings(workdir); err == nil {
			t.Fatal("null JSON must be a hard error")
		}
	})
	t.Run("empty object zero value", func(t *testing.T) {
		workdir := t.TempDir()
		testutil.WriteCheaseeSettingsFile(t, workdir, `{}`)
		s, err := LoadCheaseeSettings(workdir)
		if err != nil {
			t.Fatalf("empty {} must load, got %v", err)
		}
		if s.DefaultProvider != "" || s.Docker.Memory != "" || s.OAuth.ClientID != "" {
			t.Errorf("empty {} must yield the zero value, got %+v", s)
		}
	})
}

func TestCheaseeSettingsPath_isFolderRoot(t *testing.T) {
	workdir := filepath.Join(t.TempDir(), "ws")
	if got := cheaseeSettingsPath(workdir); got != filepath.Join(workdir, "cheasee-settings.json") {
		t.Errorf("cheaseeSettingsPath = %q, want %q", got, filepath.Join(workdir, "cheasee-settings.json"))
	}
}

// ──────────────────────────────────────────────
// CheaseeSettings.skillRepos (custom skill repositories)
// ──────────────────────────────────────────────

func TestCheaseeSettings_skillReposRoundTrip(t *testing.T) {
	workdir := t.TempDir()
	s := &CheaseeSettings{
		DefaultProvider: "opencode-go",
		SkillRepos:      []string{"https://github.com/a/b", "git:github.com/c/d@v1"},
	}
	if err := s.Save(workdir); err != nil {
		t.Fatalf("Save: %v", err)
	}
	loaded, err := LoadCheaseeSettings(workdir)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(loaded.SkillRepos) != 2 || loaded.SkillRepos[0] != "https://github.com/a/b" || loaded.SkillRepos[1] != "git:github.com/c/d@v1" {
		t.Errorf("round-trip mismatch: %v", loaded.SkillRepos)
	}
}

func TestCheaseeSettings_skillReposSaveByteStable(t *testing.T) {
	workdir := t.TempDir()
	s := &CheaseeSettings{SkillRepos: []string{"https://github.com/a/b", "git:github.com/c/d"}}
	if err := s.Save(workdir); err != nil {
		t.Fatalf("first Save: %v", err)
	}
	first, err := os.ReadFile(cheaseeSettingsPath(workdir))
	if err != nil {
		t.Fatal(err)
	}
	if err := s.Save(workdir); err != nil {
		t.Fatalf("second Save: %v", err)
	}
	second, err := os.ReadFile(cheaseeSettingsPath(workdir))
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Errorf("repeated Save with populated SkillRepos must be byte-identical:\nfirst:  %q\nsecond: %q", first, second)
	}
}

func TestCheaseeSettings_nilSkillReposOmitsKey(t *testing.T) {
	// nil SkillRepos (omitempty) must not emit a skillRepos key — the
	// existing fullCheaseeSchema round-trip/byte-stable tests stay green
	// unchanged.
	workdir := t.TempDir()
	testutil.WriteCheaseeSettingsFile(t, workdir, `{}`)
	s, err := LoadCheaseeSettings(workdir)
	if err != nil {
		t.Fatal(err)
	}
	if len(s.SkillRepos) != 0 {
		t.Fatalf("empty {} must load with nil SkillRepos, got %v", s.SkillRepos)
	}
	if err := s.Save(workdir); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(cheaseeSettingsPath(workdir))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), "skillRepos") {
		t.Errorf("Save of nil SkillRepos must not emit a skillRepos key, got: %s", data)
	}
}

func TestLoadCheaseeSettings_skillReposTypeError(t *testing.T) {
	workdir := t.TempDir()
	testutil.WriteCheaseeSettingsFile(t, workdir, `{"skillRepos": "not-an-array"}`)
	if _, err := LoadCheaseeSettings(workdir); err == nil {
		t.Fatal("string skillRepos must be a hard type error")
	}
}

// ──────────────────────────────────────────────
// CheaseeSettings unknown-key preservation (extra round-trip)
// ──────────────────────────────────────────────

func TestCheaseeSettings_preservesUnknownAndCaseVariantKeys(t *testing.T) {
	workdir := t.TempDir()
	testutil.WriteCheaseeSettingsFile(t, workdir, `{"DefaultProvider":"openai","theme":"dark","futureKey":42}`)
	s, err := LoadCheaseeSettings(workdir)
	if err != nil {
		t.Fatalf("case-variant/unknown keys must load, got %v", err)
	}
	if s.DefaultProvider != "openai" {
		t.Errorf("DefaultProvider = %q, want openai (case-insensitive key match)", s.DefaultProvider)
	}
	if err := s.Save(workdir); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(cheaseeSettingsPath(workdir))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"theme", "futureKey", `"futureKey": 42`} {
		if !strings.Contains(string(data), want) {
			t.Errorf("Save lost unknown key %q: %s", want, data)
		}
	}
}

// TestCheaseeSettings_bannerKeySurvivesLoadSaveOnce asserts the documented
// "//" banner key (the JSON-comment workaround) survives Load → Save exactly
// once — never pruned, never duplicated.
func TestCheaseeSettings_bannerKeySurvivesLoadSaveOnce(t *testing.T) {
	workdir := t.TempDir()
	banner := "Generated by cheasee-pi init. Edit this file to configure your cheasee-pi environment."
	testutil.WriteCheaseeSettingsFile(t, workdir, `{"//":"`+banner+`","defaultProvider":"openai"}`)
	s, err := LoadCheaseeSettings(workdir)
	if err != nil {
		t.Fatal(err)
	}
	if err := s.Save(workdir); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(cheaseeSettingsPath(workdir))
	if err != nil {
		t.Fatal(err)
	}
	if got := strings.Count(string(data), banner); got != 1 {
		t.Errorf("banner must survive exactly once, got %d occurrences: %s", got, data)
	}
}

// TestCheaseeSettings_saveByteStableWithExtra: a Save carrying non-nil extra
// is byte-stable across repeated saves (alphabetical key order accepted;
// only byte-stability asserted).
func TestCheaseeSettings_saveByteStableWithExtra(t *testing.T) {
	workdir := t.TempDir()
	testutil.WriteCheaseeSettingsFile(t, workdir, `{"defaultProvider":"openai","futureKey":{"nested":true}}`)
	s, err := LoadCheaseeSettings(workdir)
	if err != nil {
		t.Fatal(err)
	}
	if err := s.Save(workdir); err != nil {
		t.Fatalf("first Save: %v", err)
	}
	first, err := os.ReadFile(cheaseeSettingsPath(workdir))
	if err != nil {
		t.Fatal(err)
	}
	if err := s.Save(workdir); err != nil {
		t.Fatalf("second Save: %v", err)
	}
	second, err := os.ReadFile(cheaseeSettingsPath(workdir))
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Errorf("repeated Save with extra must be byte-identical:\nfirst:  %q\nsecond: %q", first, second)
	}
}

// TestCheaseeSettings_unwritableDirErrorsNoPartialFile: a failed cheasee Save
// must error and leave no partial/target file behind (mirror of
// TestSettingsSave_unwritableDirErrorsNoPartialFile for the cheasee path).
func TestCheaseeSettings_unwritableDirErrorsNoPartialFile(t *testing.T) {
	workdir := t.TempDir()
	if err := os.Chmod(workdir, 0555); err != nil {
		t.Fatal(err)
	}
	defer os.Chmod(workdir, 0755)

	err := (&CheaseeSettings{DefaultProvider: "openai"}).Save(workdir)
	if err == nil {
		t.Fatal("expected error writing into read-only workspace dir, got nil")
	}
	if _, statErr := os.Stat(cheaseeSettingsPath(workdir)); !os.IsNotExist(statErr) {
		t.Error("target file must be absent after failed Save (no partial write)")
	}
}
