package main

import (
	"bytes"
	"context"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
)

// ──────────────────────────────────────────────
// EnvValues
// ──────────────────────────────────────────────

// EnvValues holds the values for docker/.env generation.
type EnvValues struct {
	HostUID   string
	HostGID   string
	GitName   string
	GitEmail  string
}

// Validate checks that required values are non-empty.
func (v EnvValues) Validate() error {
	if v.HostUID == "" {
		return fmt.Errorf("HOST_UID is required")
	}
	if v.HostGID == "" {
		return fmt.Errorf("HOST_GID is required")
	}
	return nil
}

// ──────────────────────────────────────────────
// WorkdirState
// ──────────────────────────────────────────────

// WorkdirState represents the state of a working directory.
type WorkdirState int

const (
	WorkdirEmpty    WorkdirState = iota // No markers present
	WorkdirHasRepo                      // .git exists
	WorkdirHasCompose                   // docker-compose.yml exists
	WorkdirComplete                     // Both .git and docker-compose.yml exist
)

func (s WorkdirState) String() string {
	switch s {
	case WorkdirEmpty:
		return "empty"
	case WorkdirHasRepo:
		return "has-repo"
	case WorkdirHasCompose:
		return "has-compose"
	case WorkdirComplete:
		return "complete"
	default:
		return "unknown"
	}
}

// IsComplete returns true when both repo and compose markers are present.
func (s WorkdirState) IsComplete() bool {
	return s == WorkdirComplete
}

// ──────────────────────────────────────────────
// Adapter: flatEnvRenderer
// ──────────────────────────────────────────────

type flatEnvRenderer struct{}

// NewEnvRenderer creates an env renderer that writes flat KEY=VALUE lines.
func NewEnvRenderer() *flatEnvRenderer {
	return &flatEnvRenderer{}
}

func shellEscape(val string) string {
	// If the value contains whitespace or special characters, quote it.
	if strings.ContainsAny(val, " \t\n\r\"'\\$`") {
		return strconv.Quote(val)
	}
	return val
}

func (r *flatEnvRenderer) Render(_ context.Context, dest string, vals EnvValues) error {
	if err := vals.Validate(); err != nil {
		return err
	}

	dir := filepath.Dir(dest)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create env dir: %w", err)
	}

	lines := []string{
		"# Generated by cheasee-pi init",
		"HOST_UID=" + shellEscape(vals.HostUID),
		"HOST_GID=" + shellEscape(vals.HostGID),
		"HOST_GIT_NAME=" + shellEscape(vals.GitName),
		"HOST_GIT_EMAIL=" + shellEscape(vals.GitEmail),
		"",
	}
	content := strings.Join(lines, "\n")

	if err := os.WriteFile(dest, []byte(content), 0644); err != nil {
		return fmt.Errorf("write .env: %w", err)
	}
	return nil
}

// ──────────────────────────────────────────────
// Adapter: osUIDResolver
// ──────────────────────────────────────────────

type osUIDResolver struct{}

// NewUIDResolver creates a UID resolver that tries os/user.Current first,
// then falls back to $UID/$GID env vars, then id -u / id -g.
func NewUIDResolver() *osUIDResolver {
	return &osUIDResolver{}
}

func (r *osUIDResolver) Current() (uid, gid string, err error) {
	// 1. Try os/user.Current()
	if u, err := user.Current(); err == nil {
		return u.Uid, u.Gid, nil
	}

	// 2. Fallback to $UID / $GID env vars
	uid = os.Getenv("UID")
	gid = os.Getenv("GID")
	if uid != "" && gid != "" {
		return uid, gid, nil
	}

	// 3. Fallback to id -u / id -g via os/exec
	uidBytes, err := exec.Command("id", "-u").Output()
	if err != nil {
		return "", "", fmt.Errorf("all UID resolution methods failed (os/user, env, id -u): %w", err)
	}
	gidBytes, err := exec.Command("id", "-g").Output()
	if err != nil {
		return "", "", fmt.Errorf("GID resolution via id -g failed: %w", err)
	}

	return strings.TrimSpace(string(uidBytes)), strings.TrimSpace(string(gidBytes)), nil
}

// ──────────────────────────────────────────────
// Adapter: osGitIdentity
// ──────────────────────────────────────────────

type osGitIdentity struct{}

// NewGitIdentity creates a git identity resolver that shells out to git config.
func NewGitIdentity() *osGitIdentity {
	return &osGitIdentity{}
}

func (id *osGitIdentity) Lookup() (name, email string, err error) {
	// Try user.name
	nameBytes, err := exec.Command("git", "config", "--global", "user.name").Output()
	if err == nil {
		name = strings.TrimSpace(string(nameBytes))
	}

	// Try user.email
	emailBytes, err := exec.Command("git", "config", "--global", "user.email").Output()
	if err == nil {
		email = strings.TrimSpace(string(emailBytes))
	}

	return name, email, nil
}

// ──────────────────────────────────────────────
// Adapter: osWorkingDirProbe
// ──────────────────────────────────────────────

type osWorkingDirProbe struct{}

// NewWorkingDirProbe creates a probe that checks the filesystem for markers.
func NewWorkingDirProbe() *osWorkingDirProbe {
	return &osWorkingDirProbe{}
}

func (p *osWorkingDirProbe) Inspect(dir string) (WorkdirState, error) {
	hasRepo := false
	hasCompose := false

	if _, err := os.Stat(filepath.Join(dir, ".git")); err == nil {
		hasRepo = true
	}
	if _, err := os.Stat(filepath.Join(dir, "docker-compose.yml")); err == nil {
		hasCompose = true
	}

	switch {
	case hasRepo && hasCompose:
		return WorkdirComplete, nil
	case hasRepo && !hasCompose:
		return WorkdirHasRepo, nil
	case !hasRepo && hasCompose:
		return WorkdirHasCompose, nil
	default:
		return WorkdirEmpty, nil
	}
}

// ──────────────────────────────────────────────
// TemplateSettingsValues
// ──────────────────────────────────────────────

// TemplateSettingsValues holds the values for settings template substitution
// (pi's .pi/settings.json and the dedicated cheasee-settings.json). ClientID
// and DefaultModel are only referenced by the cheasee template; the pi
// template ignores them.
type TemplateSettingsValues struct {
	Provider     string
	DefaultModel string
	GitName      string
	GitEmail     string
	Memory       string
	CPUs         string
	ClientID     string
}

// ──────────────────────────────────────────────
// Adapter: templateSettingsRenderer
// ──────────────────────────────────────────────

type templateSettingsRenderer struct {
	source       fs.FS
	templatePath string
	dest         func(workdir string) string // target path for the rendered file
}

// NewSettingsScaffold creates a settings scaffold that renders the embedded
// pi/settings.json template (pi's own settings file) using text/template
// substitution. pi self-scaffolds its settings on first run; this renderer
// remains for the committed template + tests.
func NewSettingsScaffold() *templateSettingsRenderer {
	return &templateSettingsRenderer{
		source:       embeddedFS,
		templatePath: "embedded/pi/settings.json",
		dest:         func(workdir string) string { return filepath.Join(workdir, ".pi", "settings.json") },
	}
}

// NewCheaseeSettingsScaffold creates a settings scaffold that renders the
// embedded cheasee-settings.json template at the workspace root — the
// dedicated, gitignored cheasee-pi settings file whose presence marks the
// workspace initialized.
func NewCheaseeSettingsScaffold() *templateSettingsRenderer {
	return &templateSettingsRenderer{
		source:       embeddedFS,
		templatePath: "embedded/cheasee-settings.json",
		dest:         func(workdir string) string { return filepath.Join(workdir, "cheasee-settings.json") },
	}
}

func (r *templateSettingsRenderer) Scaffold(ctx context.Context, workdir string, vals TemplateSettingsValues) error {
	destPath := r.dest(workdir)

	// Idempotent: skip if file already exists.
	if _, err := os.Stat(destPath); err == nil {
		return nil
	}

	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	// Read embedded template.
	tmplContent, err := fs.ReadFile(r.source, r.templatePath)
	if err != nil {
		return fmt.Errorf("read embedded settings template: %w", err)
	}

	// Parse template.
	tmpl, err := template.New("settings").Parse(string(tmplContent))
	if err != nil {
		return fmt.Errorf("parse settings template: %w", err)
	}

	// Render to buffer, then write atomically (atomicWrite creates dirs and
	// fsyncs; no inline tmp/Rename/Remove dance needed).
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, vals); err != nil {
		return fmt.Errorf("execute settings template: %w", err)
	}
	if err := atomicWrite(destPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write settings file: %w", err)
	}

	return nil
}
