/**
 * issue-builder — Format and create GitHub issues for extension findings
 *
 * Adapter layer: calls `gh` CLI via exec function.
 */

import type { ASTFinding } from "./ast-scanner.ts";
import type { MigrationSnippet } from "./migration-generator.ts";
import type { ImpactScore } from "./impact-scorer.ts";

/** Exec function type for gh CLI subprocess calls */
export type ExecFn = (
	command: string,
	args: string[],
	options?: { cwd?: string; timeout?: number },
) => Promise<{ stdout: string; stderr: string; code: number; killed: boolean }>;

/**
 * Build issue title following spec:
 * [ext-audit] <extension-name>: <N> API changes — pi <version>
 */
export function buildIssueTitle(
	extensionName: string,
	changeCount: number,
	version: string,
): string {
	const changeWord = changeCount === 1 ? "change" : "changes";
	return `[ext-audit] ${extensionName}: ${changeCount} API ${changeWord} — pi ${version}`;
}

/**
 * Build issue body with file paths, API names, changelog ref.
 */
export function buildIssueBody(
	extensionName: string,
	findings: ASTFinding[],
	version: string,
): string {
	const lines: string[] = [];
	lines.push(`# Extension Audit: ${extensionName}`);
	lines.push(``);
	lines.push(
		`This issue tracks API changes in **pi ${version}** that affect the \`${extensionName}\` extension.`,
	);
	lines.push(``);
	lines.push(`## Changelog Reference`);
	lines.push(``);
	lines.push(`Pi version \`${version}\` contains changes that impact this extension.`);
	lines.push(``);

	// Split findings into breaking and non-breaking
	const breaking = findings.filter((f) => f.isBreaking);
	const nonBreaking = findings.filter((f) => !f.isBreaking);

	renderFindingsSection(
		lines,
		"Breaking Changes",
		"The following API changes require immediate attention:",
		breaking,
		{
			showChangelog: true,
			showCategory: true,
		},
	);

	renderFindingsSection(
		lines,
		"Simplifications & Non-Breaking Changes",
		"The following changes may simplify or improve extension code:",
		nonBreaking,
		{
			showChangelog: true,
			showCategory: true,
		},
	);

	// Migration hints
	lines.push(`## Suggested Actions`);
	lines.push(``);
	lines.push(`1. Review each finding in context`);
	lines.push(`2. Update affected API calls to match new patterns`);
	lines.push(`3. Test extension with updated APIs`);
	lines.push(`4. Close this issue when updates are complete`);
	lines.push(``);
	lines.push(`---`);
	lines.push(``);
	lines.push(`_Auto-generated by \`/check-extensions\` extension._`);

	return lines.join("\n");
}

/**
 * Check if gh CLI is authenticated.
 * Returns true if authenticated, false otherwise.
 */
export async function checkGhAuth(exec: ExecFn): Promise<boolean> {
	const result = await exec("gh", ["auth", "status"], { timeout: 10_000 });
	return result.code === 0;
}

/**
 * Ensure the extension-audit label exists on the repo.
 */
export async function ensureLabel(exec: ExecFn, repo: string): Promise<void> {
	// Check if label exists
	const listResult = await exec("gh", [
		"label",
		"list",
		"--repo",
		repo,
		"--search",
		"extension-audit",
	]);

	if (listResult.code === 0 && listResult.stdout.includes("extension-audit")) {
		return; // Label exists
	}

	// Create label
	const createResult = await exec("gh", [
		"label",
		"create",
		"extension-audit",
		"--repo",
		repo,
		"--description",
		"Extension audit tracking from /check-extensions",
		"--color",
		"A0D8F1",
	]);

	if (createResult.code !== 0) {
		throw new Error(
			`Failed to create label extension-audit: ${createResult.stderr || createResult.stdout}`,
		);
	}
}

/**
 * Check if an issue with the given title prefix already exists (open).
 * Returns true if a matching open issue exists.
 */
export async function checkExistingIssues(
	exec: ExecFn,
	repo: string,
	title: string,
): Promise<boolean> {
	// Extract prefix for search
	const prefix = title.split(":").slice(0, 2).join(":");

	const result = await exec("gh", [
		"issue",
		"list",
		"--repo",
		repo,
		"--label",
		"extension-audit",
		"--state",
		"open",
		"--search",
		prefix,
		"--json",
		"title,state,number",
	]);

	if (result.code !== 0) return false;

	try {
		const issues = JSON.parse(result.stdout);
		if (!Array.isArray(issues)) return false;

		// Check if any open issue has a matching title prefix
		return issues.some(
			(issue: { title?: string; state?: string }) =>
				issue.title?.startsWith(prefix) && issue.state === "OPEN",
		);
	} catch {
		return false;
	}
}

/**
 * Create a GitHub issue.
 * Returns the issue URL.
 */
export async function createIssue(
	exec: ExecFn,
	repo: string,
	title: string,
	body: string,
): Promise<string> {
	const result = await exec("gh", [
		"issue",
		"create",
		"--repo",
		repo,
		"--title",
		title,
		"--body",
		body,
		"--label",
		"extension-audit",
	]);

	if (result.code !== 0) {
		throw new Error(`Failed to create issue: ${result.stderr || result.stdout}`);
	}

	return result.stdout.trim();
}

// ── Extended Issue Building (Phase 3: Rich output) ───────────────────

/**
 * Build a Migration Guide section for an issue body.
 *
 * @param snippets - Array of migration snippets
 * @returns Markdown section string, or empty string if no snippets
 */
export function buildMigrationSection(snippets: MigrationSnippet[]): string {
	if (snippets.length === 0) return "";

	const lines: string[] = [];
	lines.push("## Migration Guide");
	lines.push("");
	lines.push("The following code snippets show how to update affected API calls:");
	lines.push("");

	for (const snippet of snippets) {
		const confidenceLabel =
			snippet.confidence >= 0.7
				? "✅ High confidence"
				: snippet.confidence >= 0.3
					? "⚠️ Medium confidence — review required"
					: "❌ Low confidence — manual migration needed";

		lines.push(`### \`${snippet.apiName}\` — ${confidenceLabel}`);
		lines.push("");
		lines.push("**Before:**");
		lines.push("");
		lines.push("```ts");
		lines.push(snippet.before);
		lines.push("```");
		lines.push("");
		lines.push("**After:**");
		lines.push("");
		lines.push("```ts");
		lines.push(snippet.after);
		lines.push("```");
		lines.push("");
	}

	return lines.join("\n");
}

/**
 * Build an Impact Summary section for an issue body.
 *
 * @param score - Impact score for the extension
 * @returns Markdown summary string
 */
export function buildImpactSummary(score: ImpactScore): string {
	const severityEmoji: Record<string, string> = {
		none: "✅",
		low: "🟢",
		medium: "🟡",
		high: "🔴",
		critical: "🚨",
	};

	const emoji = severityEmoji[score.severity] ?? "❓";
	const testsBadge = score.hasTests ? "✅" : "❌";

	const lines: string[] = [];
	lines.push("## Impact Summary");
	lines.push("");
	const severityLabel = score.severity.charAt(0).toUpperCase() + score.severity.slice(1);
	lines.push(`${emoji} **Severity:** ${severityLabel}`);
	lines.push(`- **Affected APIs:** ${score.uniqueApis}`);
	lines.push(`- **Breaking changes:** ${score.breakingCount}`);
	lines.push(`- **Tests:** ${testsBadge}`);
	lines.push("");

	return lines.join("\n");
}

/**
 * Build a full issue body with migration snippets and impact scoring.
 * Extends buildIssueBody with richer content.
 *
 * @param extensionName - Name of the extension
 * @param findings - Array of AST findings
 * @param version - Pi version from changelog
 * @param snippets - Migration snippets (may be empty)
 * @param impactScore - Impact score for this extension
 * @returns Complete markdown issue body
 */
export function buildIssueBodyWithSnippets(
	extensionName: string,
	findings: ASTFinding[],
	version: string,
	snippets: MigrationSnippet[],
	impactScore: ImpactScore,
): string {
	const lines: string[] = [];

	lines.push(`# Extension Audit: ${extensionName}`);
	lines.push("");
	lines.push(
		`This issue tracks API changes in **pi ${version}** that affect the \`${extensionName}\` extension.`,
	);
	lines.push("");

	// Impact Summary
	lines.push(buildImpactSummary(impactScore));

	// Changelog Reference
	lines.push("## Changelog Reference");
	lines.push("");
	lines.push(`Pi version \`${version}\` contains changes that impact this extension.`);
	lines.push("");

	// Breaking changes
	const breaking = findings.filter((f) => f.isBreaking);
	const nonBreaking = findings.filter((f) => !f.isBreaking);

	renderFindingsSection(
		lines,
		"Breaking Changes",
		"The following API changes require immediate attention:",
		breaking,
		{
			showCallArgs: true,
		},
	);

	// Non-breaking changes
	renderFindingsSection(
		lines,
		"Simplifications & Non-Breaking Changes",
		"The following changes may simplify or improve extension code:",
		nonBreaking,
		{
			showCallArgs: true,
		},
	);

	// Migration Guide section
	if (snippets.length > 0) {
		lines.push(buildMigrationSection(snippets));
	}

	// Suggested Actions
	lines.push("## Suggested Actions");
	lines.push("");
	lines.push("1. Review each finding in context");
	lines.push("2. Apply migration snippets where provided (review low-confidence ones)");
	lines.push("3. Update affected API calls to match new patterns");
	lines.push("4. Test extension with updated APIs");
	lines.push("5. Close this issue when updates are complete");
	lines.push("");
	lines.push("---");
	lines.push("");
	lines.push("_Auto-generated by \`/check-extensions\` extension._");

	return lines.join("\n");
}

/**
 * Render a findings section with common template structure.
 *
 * Pure function — pushes markdown lines directly into the provided array.
 * Used to eliminate duplicated template logic across issue body builders.
 *
 * @param lines - Target array to push markdown lines into
 * @param title - Section heading (without ## prefix)
 * @param description - Section description paragraph
 * @param findings - Findings to render
 * @param options - Rendering options
 *   - showCallArgs: when true, shows context badge in heading and Args line
 *   - showChangelog: when true, shows Changelog line per finding
 *   - showCategory: when true, shows — category in heading (used by buildIssueBody)
 */
export function renderFindingsSection(
	lines: string[],
	title: string,
	description: string,
	findings: ASTFinding[],
	options?: { showCallArgs?: boolean; showChangelog?: boolean; showCategory?: boolean },
): void {
	if (findings.length === 0) return;
	lines.push(`## ${title}`);
	lines.push(``);
	lines.push(description);
	lines.push(``);
	for (const f of findings) {
		let heading = `### \`${f.apiName}\``;
		if (options?.showCallArgs) {
			heading += ` ${getContextBadge(f.matchContext)}`;
		} else if (options?.showCategory) {
			heading += ` — ${f.category}`;
		}
		lines.push(heading);
		lines.push(``);
		lines.push(`- **File:** \`${f.file}\``);
		lines.push(`- **Line:** ${f.line}`);
		lines.push(`- **Code:** \`${f.lineContent}\``);
		if (options?.showCallArgs && f.callArgs?.length > 0) {
			lines.push(`- **Args:** \`${f.callArgs.join(", ")}\``);
		}
		if (options?.showChangelog) {
			lines.push(`- **Changelog:** ${f.changelogVersion}`);
		}
		lines.push(``);
	}
}

/**
 * Get a short emoji badge for match context type.
 */
export function getContextBadge(context: string): string {
	const badges: Record<string, string> = {
		"runtime-call": "⚡",
		"import-type": "📦",
		"import-value": "📥",
		comment: "💬",
		"string-literal": "🔤",
		"dead-code": "💀",
	};
	return badges[context] ?? "❓";
}
