/**
 * pipeline — ChangelogPipeline: extracted pipeline runner for /check-extensions
 *
 * Each phase is a method, making the pipeline testable independently.
 * Constants live in constants.ts; this file owns the orchestration.
 */

import fs, { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

import { PI_CHANGELOG_PATH, API_PATTERNS, CHANGELOG_API_TO_PATTERN_LOWER } from "./constants.ts";
import { parseChangelog, parseStructuredChange, type ChangeEntry } from "./changelog-parser.ts";
import { scanExtensionsAST, type ASTFinding, type ExecFn as AstExecFn } from "./ast-scanner.ts";
import { resolveRelevance } from "./change-resolver.ts";
import { computeImpactScore, type ImpactScore } from "./impact-scorer.ts";
import { generateMigrationSnippet, type MigrationSnippet } from "./migration-generator.ts";

// ─── Helpers ──────────────────────────────────────────────────────────

/**
 * Resolve the path to ast-grep binary.
 * Checks common locations, falls back to "ast-grep" (PATH).
 */
export function resolveAstGrepPath(): string {
	const home = process.env.HOME || homedir();
	const candidates = [
		join(home, ".npm-global", "bin", "ast-grep"),
		"/usr/local/bin/ast-grep",
		"/usr/bin/ast-grep",
	];
	for (const c of candidates) {
		try {
			fs.accessSync(c, fs.constants.F_OK);
			return c;
		} catch {
			/* try next */
		}
	}
	return "ast-grep"; // fallback — hope it's on PATH
}

/** Context object passed to pipeline (subset of pi extension context) */
export interface PipelineContext {
	cwd: string;
	ui: {
		notify: (msg: string, level: "info" | "error" | "warning") => void;
	};
	/** True when the UI supports transient notifications (TUI/RPC modes) */
	hasUI: boolean;
}

/** Report generated by the pipeline */
export interface PipelineReport {
	lines: string[];
	createdIssues: Array<{ extName: string; url: string }>;
	skippedExtensions: string[];
	findingsByExtension: Map<string, ASTFinding[]>;
	totalFindings: number;
}

/**
 * ChangelogPipeline — orchestrates the /check-extensions audit flow.
 *
 * Phases:
 *   0. validatePhase — check prerequisites
 *   1. parsePhase — parse pi CHANGELOG.md
 *   2. scanPhase — scan .pi/extensions/ with ast-grep
 *   2.5 crossRefPhase — cross-reference, relevance, score, snippets
 *   3. issuePhase — create GitHub issues
 */
export class ChangelogPipeline {
	private pi: ExtensionAPI;
	private ctx: PipelineContext;
	private report: PipelineReport;

	constructor(pi: ExtensionAPI, ctx: PipelineContext) {
		this.pi = pi;
		this.ctx = ctx;
		this.report = {
			lines: [],
			createdIssues: [],
			skippedExtensions: [],
			findingsByExtension: new Map(),
			totalFindings: 0,
		};
	}

	/**
	 * Notify the user — adapts to UI mode.
	 * In UI modes (TUI/RPC), uses ctx.ui.notify for transient notifications.
	 * In non-UI modes (JSON/print), falls back to pi.sendMessage for structured messages.
	 * Catches sendMessage rejections to prevent unhandled promise rejections.
	 */
	private notify(msg: string, level: "info" | "error" | "warning"): void {
		if (this.ctx.hasUI) {
			this.ctx.ui.notify(msg, level);
		} else {
			try {
				this.pi.sendMessage({
					customType: "check-extensions",
					content: msg,
					display: true,
				});
			} catch {
				/* sendMessage failure is non-critical */
			}
		}
	}

	/** Run the full pipeline. Returns the report. */
	async run(): Promise<PipelineReport> {
		// Phase 0: Validate
		const changelogContent = this.validatePhase();
		if (!changelogContent) {
			this.pi.sendUserMessage(this.report.lines.join("\n"));
			return this.report;
		}

		// Phase 1: Parse changelog
		const { entries, latestVersion, affectedApiPatterns } = this.parsePhase(changelogContent);

		// Phase 2: Scan extensions
		const scanResult = await this.scanPhase(entries, latestVersion, affectedApiPatterns);
		if (!scanResult) {
			this.pi.sendUserMessage(this.report.lines.join("\n"));
			return this.report;
		}
		const { scanResult: scan, findingsByExtension } = scanResult;

		// Phase 2.5: Cross-reference
		const { relevantFindingsByExtension, snippetsByExtension, scoresByExtension } =
			this.crossRefPhase(entries, latestVersion, findingsByExtension, scan);

		if (relevantFindingsByExtension.size === 0) {
			this.pi.sendUserMessage(this.report.lines.join("\n"));
			return this.report;
		}

		// Phase 3: Create issues
		await this.issuePhase(
			relevantFindingsByExtension,
			snippetsByExtension,
			scoresByExtension,
			latestVersion,
		);

		this.report.lines.push("");
		this.report.lines.push("---");
		this.report.lines.push(
			`_Scanned ${findingsByExtension.size} extension(s), ` +
				`${scan.findings.length} total finding(s)._`,
		);

		this.pi.sendUserMessage(this.report.lines.join("\n"));
		this.notify("Evaluation request sent to agent — LLM will decide on issues.", "info");

		return this.report;
	}

	// ── Phase 0: Validate prerequisites ──────────────────────────────

	/**
	 * Validate that pi CHANGELOG.md exists.
	 * Returns the file content, or null on failure (error already reported).
	 */
	validatePhase(): string | null {
		if (!existsSync(PI_CHANGELOG_PATH)) {
			const msg = `Pi changelog not found at ${PI_CHANGELOG_PATH}`;
			this.notify(msg, "error");
			this.report.lines.push(`❌ ${msg}`);
			return null;
		}

		this.notify("Parsing pi CHANGELOG...", "info");
		try {
			return readFileSync(PI_CHANGELOG_PATH, "utf-8");
		} catch (err) {
			const msg = `Failed to read changelog: ${(err as Error).message}`;
			this.notify(msg, "error");
			this.pi.sendUserMessage(msg);
			return null;
		}
	}

	// ── Phase 1: Parse changelog ─────────────────────────────────────

	/**
	 * Parse changelog content into entries, extract latest version,
	 * and collect affected API patterns.
	 */
	parsePhase(changelogContent: string): {
		entries: ChangeEntry[];
		latestVersion: string;
		affectedApiPatterns: Set<string>;
	} {
		const allEntries = parseChangelog(changelogContent);
		if (allEntries.length === 0) {
			this.notify("No API changes found in changelog.", "info");
			this.report.lines.push("No API-visible changes detected in pi changelog.");
			this.report.lines.push("");
			this.report.lines.push("Scanned extensions for current API usage anyway (no reference).");
		}

		const latestVersion = allEntries.length > 0 ? allEntries[0]!.version : "latest";

		// ponytail: only scan last major.minor stream — older breaking changes
		// are irrelevant to current extensions. Add --since flag if depth needed.
		const latestBase = latestVersion.split(".").slice(0, 2).join(".");
		const entries = allEntries.filter((e) => e.version.startsWith(latestBase + "."));

		// Collect unique API names from changelog entries
		const affectedApiPatterns = new Set<string>();
		for (const entry of entries) {
			for (const apiName of entry.apiNames) {
				const patterns = CHANGELOG_API_TO_PATTERN_LOWER[apiName.toLowerCase()];
				if (patterns) {
					for (const p of patterns) affectedApiPatterns.add(p);
				}
			}
		}

		// If no specific API patterns found, scan all patterns
		if (affectedApiPatterns.size === 0) {
			for (const p of API_PATTERNS) affectedApiPatterns.add(p);
		}

		return { entries, latestVersion, affectedApiPatterns };
	}

	// ── Phase 2: Scan extensions ─────────────────────────────────────

	/**
	 * Scan .pi/extensions/ directory with ast-grep.
	 * Returns scan result and findings grouped by extension,
	 * or null if no findings (already reported).
	 */
	async scanPhase(
		entries: ChangeEntry[],
		latestVersion: string,
		affectedApiPatterns: Set<string>,
	): Promise<{
		scanResult: Awaited<ReturnType<typeof scanExtensionsAST>>;
		findingsByExtension: Map<string, ASTFinding[]>;
	} | null> {
		this.notify("Scanning .pi/extensions/ with ast-grep...", "info");
		const extensionsDir = join(this.ctx.cwd, ".pi", "extensions");
		const apiNamesList = Array.from(affectedApiPatterns);
		const astGrepPath = resolveAstGrepPath();

		const scanResult = await scanExtensionsAST(
			extensionsDir,
			apiNamesList,
			this.pi.exec.bind(this.pi) as unknown as AstExecFn,
			astGrepPath,
		);

		if (scanResult.skipCount > 0) {
			this.report.lines.push(`⚠️ ${scanResult.skipCount} file(s) could not be read (skipped).`);
		}

		if (scanResult.findings.length === 0) {
			const msg = "All extensions compatible with latest pi changelog.";
			this.notify(msg, "info");
			this.report.lines.push(msg);
			return null;
		}

		// Group findings by extension
		const findingsByExtension = new Map<string, ASTFinding[]>();
		for (const finding of scanResult.findings) {
			const extName = finding.extensionName;
			if (!findingsByExtension.has(extName)) {
				findingsByExtension.set(extName, []);
			}
			findingsByExtension.get(extName)!.push(finding);
		}

		return { scanResult, findingsByExtension };
	}

	// ── Phase 2.5: Cross-reference ───────────────────────────────────

	/**
	 * Cross-reference findings with changelog entries, resolve relevance,
	 * compute impact scores, and generate migration snippets.
	 */
	crossRefPhase(
		entries: ChangeEntry[],
		latestVersion: string,
		findingsByExtension: Map<string, ASTFinding[]>,
		scanResult: Awaited<ReturnType<typeof scanExtensionsAST>>,
	): {
		relevantFindingsByExtension: Map<string, ASTFinding[]>;
		snippetsByExtension: Map<string, MigrationSnippet[]>;
		scoresByExtension: Map<string, ImpactScore>;
	} {
		const snippetsByExtension = new Map<string, MigrationSnippet[]>();
		const scoresByExtension = new Map<string, ImpactScore>();

		for (const [extName, extFindings] of findingsByExtension) {
			const extSnippets: MigrationSnippet[] = [];

			for (const f of extFindings) {
				f.changelogVersion = latestVersion;

				// Find matching changelog entry by API name
				const matchingEntry = findMatchingEntry(f.apiName, entries);
				if (matchingEntry) {
					f.isBreaking = matchingEntry.isBreaking;
					f.category = matchingEntry.category;

					// Parse structured change and resolve relevance
					const structuredChange = parseStructuredChange(matchingEntry.description);
					if (structuredChange) {
						const relevant = resolveRelevance(matchingEntry, f, structuredChange);
						if (relevant === false) {
							// False positive — changelog change doesn't affect this call
							f.category = "not-applicable";
						}
					}

					// Generate migration snippet for runtime-call findings
					if (f.matchContext === "runtime-call") {
						const snippet = generateMigrationSnippet(matchingEntry.description, f.apiName);
						if (snippet) {
							extSnippets.push(snippet);
						}
					}
				}
			}

			snippetsByExtension.set(extName, extSnippets);
		}

		// Filter out extensions where all findings are non-applicable
		// AND compute impact scores using only relevant (non-not-applicable) findings
		const relevantFindingsByExtension = new Map<string, ASTFinding[]>();
		for (const [extName, extFindings] of findingsByExtension) {
			const relevant = extFindings.filter((f) => f.category !== "not-applicable");
			if (relevant.length > 0) {
				relevantFindingsByExtension.set(extName, relevant);

				// Compute impact score using only relevant findings
				const score = computeImpactScore(extName, relevant);
				scoresByExtension.set(extName, score);
			}
		}

		if (relevantFindingsByExtension.size === 0) {
			const msg = "All findings resolved as non-applicable after changelog cross-reference.";
			this.notify(msg, "info");
			this.report.lines.push(msg);
		}

		return {
			relevantFindingsByExtension,
			snippetsByExtension,
			scoresByExtension,
		};
	}

	// ── Phase 3: Present findings to agent for LLM evaluation ────────

	/**
	 * Send findings to the current session agent (the LLM) for evaluation.
	 * The extension collects + scores findings, then asks the agent to
	 * decide what's worth creating issues for.
	 */
	async issuePhase(
		relevantFindingsByExtension: Map<string, ASTFinding[]>,
		_snippetsByExtension: Map<string, MigrationSnippet[]>,
		scoresByExtension: Map<string, ImpactScore>,
		latestVersion: string,
	): Promise<void> {
		if (relevantFindingsByExtension.size === 0) return;

		// Build structured evaluation request
		const lines: string[] = [];
		lines.push(`## Extension Audit: Findings vs pi ${latestVersion}`);
		lines.push("");
		lines.push(
			"The check-extensions scanner found these findings. Evaluate each and create GitHub issues for the ones worth tracking.",
		);
		lines.push("");
		lines.push("### Criteria for creating an issue");
		lines.push("- **YES** if findings include breaking changes (Removed/Deprecated APIs)");
		lines.push("- **YES** if non-breaking but still worth tracking (important migration needed)");
		lines.push("- **SKIP** if findings are only import references with no behavioral impact");
		lines.push(
			"- **SKIP** if findings are low-severity non-breaking changes that don't need tracking",
		);
		lines.push("- **SKIP** if extension already handles/mitigates the change");
		lines.push("");

		for (const [extName, extFindings] of relevantFindingsByExtension) {
			const score = scoresByExtension.get(extName);
			const sev = score
				? `${score.severity} (${score.breakingCount} breaking, ${score.uniqueApis} APIs)`
				: "unknown";

			lines.push(`#### ${extName} — severity: ${sev}`);
			lines.push("");
			for (const f of extFindings) {
				const breaking = f.isBreaking ? " ⚠️ breaking" : "";
				lines.push(`- \`${f.apiName}\` in \`${f.file}:${f.line}\` — ${f.category}${breaking}`);
			}
			lines.push("");
		}

		lines.push("---");
		lines.push(
			'_Use \`gh issue create --repo REPO --title "..." --body "..." --label extension-audit\` to create issues for approved extensions._',
		);

		const msg = lines.join("\n");

		// Send to agent — the LLM (current session) evaluates and creates issues
		this.pi.sendUserMessage(msg);
	}
}

/**
 * Find ALL changelog entries matching a given API name, then return the most
 * severe one (breaking > non-breaking; Removed > Deprecated > Changed > Added > Fixed).
 *
 * Because changelogs are ordered newest-first per Keep a Changelog, the previous
 * implementation using Array.find() returned only the latest entry, silently masking
 * older breaking changes for the same API.
 */
function findMatchingEntry(apiName: string, entries: ChangeEntry[]): ChangeEntry | undefined {
	const normalized = apiName.replace(/^pi\./, "").replace(/^ctx\./, "");
	const matching = entries.filter((e) =>
		e.apiNames.some(
			(name) =>
				name.toLowerCase() === apiName.toLowerCase() ||
				name.toLowerCase() === normalized.toLowerCase(),
		),
	);
	if (matching.length === 0) return undefined;

	// Severity ordering: higher number = more severe.
	// Removed and Deprecated are breaking; Changed, Added, Fixed, Security are non-breaking.
	const severity: Record<string, number> = {
		Removed: 5,
		Deprecated: 4,
		Changed: 3,
		Security: 2,
		Added: 1,
		Fixed: 0,
		"New Features": 0,
	};

	// Stable sort: entries with the same category retain their original order (newest-first).
	matching.sort((a, b) => (severity[b.category] ?? 0) - (severity[a.category] ?? 0));
	return matching[0];
}

/**
 * Parsed args structure (from local parseArgs wrapper).
 */
export interface ParsedArgs {
	unknownFlags: Map<string, boolean | string>;
	messages: string[];
}

/**
 * Create and run a ChangelogPipeline instance.
 * Convenience function for index.ts wiring.
 * Accepts optionally parsed args for future flag support.
 */
export async function runPipeline(
	pi: ExtensionAPI,
	ctx: PipelineContext,
	_parsedArgs?: ParsedArgs,
): Promise<PipelineReport> {
	const pipeline = new ChangelogPipeline(pi, ctx);
	return pipeline.run();
}
